apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: counter
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lakhan361/interview:2
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "demo.py"
        command: ["sh"]
        args: ["-c","flask run --host=0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-public
  namespace: counter
spec:
  type: NodePort
  ports:
  - port: 8008
    protocol: TCP
    targetPort: 5000
    nodePort: 80
  selector:
      app: frontend
